# Generated by Django 5.1.2 on 2024-12-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_remove_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_asistencia',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_salida',
        ),
    ]
