# Generated by Django 5.1.2 on 2024-12-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0003_remove_asistencia_fecha_asistencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='cliente',
        ),
        migrations.AddField(
            model_name='membresia',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gimnasio.pago'),
            preserve_default=False,
        ),
    ]
